export {default as FormInput} from './FromInput'
export {default as SubmitBtn} from './SubmitBtn'
export {default as Header} from './Header'
export {default as Hero} from './Hero'
export {default as ErrorElement} from './ErrorElement'
export {default as SectionTitle} from './SectionTitle'
export {default as ProductsGrid} from './ProductsGrid'
export {default as FeaturedProducts} from './FeaturedProducts'
export {default as PaginationContainer} from './PaginationContainer'
export {default as ProductsContainer} from './ProductsContainer'
export {default as CartItemsList} from './CartItem'
export {default as CartTotals} from './CartItem'
export {default as Loading} from './Loading'
export {default as Navbar} from './Navbar'
// export {default as CartItemsList} from './CartItemsList'
// export {default as CartTotals} from './CartTotals'